server.port=${PORT:8000}
server.shutdown=immediate
server.tomcat.threads.max=50
server.tomcat.accept-count=50

spring.application.name=springboot-app
spring.jmx.enabled=false
spring.main.banner-mode=off
spring.main.lazy-initialization=true

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

spring.thymeleaf.cache=true

logging.pattern.console=[%level] %logger{36}: %msg%n
logging.level.lowops=INFO
logging.level.org.springframework=WARN
logging.level.org.apache.catalina=WARN
logging.level.org.apache.tomcat=WARN
