server.port=${PORT:8000}

spring.application.name=springboot-app

spring.autoconfigure.exclude=\
  org.springframework.boot.jdbc.autoconfigure.DataSourceAutoConfiguration,\
  org.springframework.boot.jdbc.autoconfigure.DataSourceTransactionManagerAutoConfiguration,\
  org.springframework.boot.jdbc.autoconfigure.JdbcTemplateAutoConfiguration,\
  org.springframework.boot.sql.init.autoconfigure.SqlInitializationAutoConfiguration

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

spring.thymeleaf.cache=${THYMELEAF_CACHE:false}

logging.pattern.console=[%level] %logger{36}: %msg%n
logging.level.lowops=INFO
